" nmap <Leader>bt <Plug>(coc-bookmark-toggle)
" nmap <Leader>ba <Plug>(coc-bookmark-annotate)
" nmap <Leader>bj <Plug>(coc-bookmark-next)
" nmap <Leader>bk <Plug>(coc-bookmark-prev)
" " nmap <Leader>bc <Plug>(coc-bookmark-clearForCurrentFile)
" " nmap <Leader>bC <Plug>(coc-bookmark-clearForAllFiles)
